//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_order
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string SecurityCode { get; set; }
        public string SecurityName { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<decimal> TransactionPrice { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public Nullable<decimal> CounterFee { get; set; }
        public Nullable<decimal> StampDuty { get; set; }
        public Nullable<decimal> OtherExpenses { get; set; }
        public Nullable<decimal> OccurrenceAmount { get; set; }
        public string Remark { get; set; }
        public string Operation { get; set; }
        public Nullable<int> OperationType { get; set; }
        public string ClosingDate { get; set; }
    }
}
