//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQY_ManageEntities : DbContext
    {
        public SQY_ManageEntities()
            : base("name=SQY_ManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<delivery_order> delivery_order { get; set; }
        public virtual DbSet<group_menu_mapping> group_menu_mapping { get; set; }
        public virtual DbSet<stock_exchange_record> stock_exchange_record { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
        public virtual DbSet<sys_user_group> sys_user_group { get; set; }
        public virtual DbSet<sys_user_menu> sys_user_menu { get; set; }
        public virtual DbSet<turn_in_out_record> turn_in_out_record { get; set; }
        public virtual DbSet<user_group_mapping> user_group_mapping { get; set; }
        public virtual DbSet<water_bill> water_bill { get; set; }
        public virtual DbSet<stock> stock { get; set; }
    }
}
