//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_user_menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_user_menu()
        {
            this.group_menu_mapping = new HashSet<group_menu_mapping>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string STitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ControllName { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> SortValue { get; set; }
        public bool State { get; set; }
        public Nullable<bool> IsPath { get; set; }
        public Nullable<bool> ShowInMenu { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group_menu_mapping> group_menu_mapping { get; set; }
    }
}
