//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Stock
    {
        public int Id { get; set; }
        public string StockCode { get; set; }
        public string FullCode { get; set; }
        public string StockName { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalMarketValue { get; set; }
        public Nullable<decimal> CirculationMarketValue { get; set; }
        public int Industry { get; set; }
        public string PyAbbre { get; set; }
        public string PyFullName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
