//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliYunModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AliDbEntities : DbContext
    {
        public AliDbEntities()
            : base("name=AliDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoSignHistory> AutoSignHistory { get; set; }
        public virtual DbSet<AutoSignUser> AutoSignUser { get; set; }
        public virtual DbSet<MansUser> MansUser { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<WeixinCustomer> WeixinCustomer { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Customer_MansUser_Mapping> Customer_MansUser_Mapping { get; set; }
        public virtual DbSet<ZhihuAnswer> ZhihuAnswer { get; set; }
        public virtual DbSet<ZhihuReadHistory> ZhihuReadHistory { get; set; }
    }
}
