//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliYunModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoSignHistory
    {
        public int Id { get; set; }
        public int MansUserId { get; set; }
        public System.DateTime SignDateTime { get; set; }
        public int SignType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
