//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliYunModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string RealName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string WeixinId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string HeadImg { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int Status { get; set; }
        public Nullable<int> SupervisorCustomerId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
