//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliYunModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MansUser
    {
        public int Id { get; set; }
        public string LeShareUserName { get; set; }
        public string RealName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string HeadImg { get; set; }
        public string LeSharePwd { get; set; }
        public Nullable<bool> IsAutoSign { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
