//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliYunModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeixinCustomer
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string OpenId { get; set; }
        public string Nickname { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string HeadImg { get; set; }
        public string Language { get; set; }
        public Nullable<System.DateTime> SubscribeDate { get; set; }
        public Nullable<bool> UnSubscribed { get; set; }
        public Nullable<System.DateTime> UnSubscribeDate { get; set; }
        public System.DateTime CreateOn { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> LastActivityTime { get; set; }
    }
}
