//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliYunModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZhihuAnswer
    {
        public int Id { get; set; }
        public string QuestionId { get; set; }
        public string AnswerId { get; set; }
        public string Question { get; set; }
        public string Author { get; set; }
        public string Bio { get; set; }
        public string Summary { get; set; }
        public string Content { get; set; }
        public Nullable<int> ZanCount { get; set; }
        public bool Recommended { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool deleted { get; set; }
    }
}
