CREATE TABLE Customer(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	Username VARCHAR(500) NULL,
	Email VARCHAR(200) NULL,
	Mobile VARCHAR(200) NULL,
	Password VARCHAR(500) NULL,
	Realname VARCHAR(200) NULL,
	LastIpAddress VARCHAR(200) NULL,
	LastLoginOn DATETIME NULL,
	CreateOn DATETIME NOT NULL,
	Deleted BIT NOT NULL DEFAULT 0,
)

GO


CREATE TABLE CustomerRole(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	Name VARCHAR(200) NOT NULL,
	Describe VARCHAR(500) NULL,
	Deleted BIT NOT NULL,
)
GO

CREATE TABLE Customer_CustomerRole_Mapping(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	Customer_Id INT NOT NULL FOREIGN KEY REFERENCES dbo.Customer,
	CustomerRole_Id INT NOT NULL  FOREIGN KEY REFERENCES dbo.CustomerRole,
)
GO

CREATE TABLE WeixinCustomer(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	CustomerId INT NULL,
	OpenId VARCHAR(200) NOT NULL,
	Nickname NVARCHAR(200) NULL,
	Gender BIT NULL,
	Country NVARCHAR(200) NULL,
	Province NVARCHAR(200) NULL,
	City NVARCHAR(200) NULL,
	HeadImg VARCHAR(500) NULL,
	Language VARCHAR(100) NULL,
	SubscribeDate DATETIME NULL,
	LastActivityTime DATETIME NULL,
	UnSubscribed BIT NULL,
	UnSubscribeDate DATETIME NULL,
	CreateOn DATETIME NOT NULL,
	ModifyOn DATETIME NOT NULL,
	Deleted BIT NOT NULL DEFAULT 0,
)

GO
