//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_menu_mapping
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int MenuID { get; set; }
    
        public virtual sys_user_group sys_user_group { get; set; }
        public virtual sys_user_menu sys_user_menu { get; set; }
    }
}
